<fmt:message key="dashboard.description" bundle="${curr_locale}" var="dashboardInfo" />
<fmt:message key="dashboard.profiles" bundle="${curr_locale}" var="profiles" />
<fmt:message key="dashboard.profilesInfo" bundle="${curr_locale}" var="profilesInfo" />
<fmt:message key="dashboard.profilesBlockUser" bundle="${curr_locale}" var="blockUser" />
<fmt:message key="dashboard.profilesChangeUserRole" bundle="${curr_locale}" var="changeUserRole" />
<fmt:message key="dashboard.things" bundle="${curr_locale}" var="things" />
<fmt:message key="dashboard.thingsInfo" bundle="${curr_locale}" var="thingsInfo" />
<fmt:message key="dashboard.categories" bundle="${curr_locale}" var="categories" />
<fmt:message key="dashboard.categoriesInfo" bundle="${curr_locale}" var="categoriesInfo" />
<fmt:message key="dashboard.brands" bundle="${curr_locale}" var="brands" />
<fmt:message key="dashboard.brandsInfo" bundle="${curr_locale}" var="brandsInfo" />
<fmt:message key="dashboard.photos" bundle="${curr_locale}" var="photos" />
<fmt:message key="dashboard.photosInfo" bundle="${curr_locale}" var="photosInfo" />
<fmt:message key="dashboard.reviews" bundle="${curr_locale}" var="reviews" />
<fmt:message key="dashboard.reviewsInfo" bundle="${curr_locale}" var="reviewsInfo" />
<fmt:message key="dashboard.products" bundle="${curr_locale}" var="products" />
<fmt:message key="dashboard.productsInfo" bundle="${curr_locale}" var="productsInfo" />
<fmt:message key="dashboard.productsThings" bundle="${curr_locale}" var="productsThings" />
<fmt:message key="dashboard.productsThingsInfo" bundle="${curr_locale}" var="productsThingsInfo" />
<fmt:message key="dashboard.discounts" bundle="${curr_locale}" var="discounts" />
<fmt:message key="dashboard.discountsInfo" bundle="${curr_locale}" var="discountsInfo" />
<fmt:message key="dashboard.buttonsTextAdd" bundle="${curr_locale}" var="btnAdd" />
<fmt:message key="dashboard.buttonsTextCreate" bundle="${curr_locale}" var="btnCreate" />
<fmt:message key="dashboard.buttonsTextUpdate" bundle="${curr_locale}" var="btnUpdate" />
<fmt:message key="dashboard.buttonsTextDelete" bundle="${curr_locale}" var="btnDelete" />