package com.training.web_store.command;

public enum CommandName {
    SIGN_UP,
    SIGN_IN,
    SIGN_OUT,

    CHANGE_LOCALE,

    CREATE_BRAND,
    CREATE_CATEGORY,
    CREATE_THING,
    CREATE_REVIEW,
    ADD_PHOTO,
    CREATE_PRODUCT,
    ADD_TO_PRODUCT,
    REMOVE_FROM_PRODUCT,
    CREATE_DISCOUNT,

    SHOW_PRODUCT,
    SEARCH_PRODUCT,
    SHOW_PRODUCTS,

    UPDATE_PRODUCT,
    UPDATE_THING,
    UPDATE_CATEGORY,
    UPDATE_BRAND,
    UPDATE_DISCOUNT,

    REMOVE_PRODUCT,
    REMOVE_THING,
    REMOVE_CATEGORY,
    REMOVE_BRAND,
    REMOVE_DISCOUNT,
    REMOVE_PHOTO,

    RATE_THING,
    ADD_TO_ORDER,
    REMOVE_FROM_ORDER,
    BUY_ORDER,

    WRONG,
}
