<fmt:message key="names.titleIm" bundle="${curr_locale}" var="title" />
<fmt:message key="names.aboutIm" bundle="${curr_locale}" var="about" />
<fmt:message key="userInfo.firstName" bundle="${curr_locale}" var="firstName" />
<fmt:message key="userInfo.lastName" bundle="${curr_locale}" var="lastName" />
<fmt:message key="userInfo.address" bundle="${curr_locale}" var="address" />
<fmt:message key="userInfo.phone" bundle="${curr_locale}" var="phone" />
<fmt:message key="userInfo.gender" bundle="${curr_locale}" var="gender" />
<fmt:message key="userInfo.genderMale" bundle="${curr_locale}" var="male" />
<fmt:message key="userInfo.genderFemale" bundle="${curr_locale}" var="female" />
<fmt:message key="buttons.logout" bundle="${curr_locale}" var="logout" />
<fmt:message key="errors.userNotFound" bundle="${curr_locale}" var="errorNotFound" />
